[package]
name = "noodles-gff"
version = "0.11.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license.workspace = true
edition.workspace = true
rust-version = "1.64.0"
description = "Generic Feature Format (GFF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-gff"

[dependencies]
noodles-core = { path = "../noodles-core", version = "0.11.0" }
percent-encoding.workspace = true
