[package]
name = "noodles-gff"
version = "0.5.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.56.0"
description = "Generic Feature Format (GFF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-gff"

[dependencies]
noodles-core = { path = "../noodles-core", version = "0.5.0" }
percent-encoding = "2.1.0"
