[package]
name = "noodles-gff"
version = "0.3.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Generic Feature Format (GFF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-gff"

[dependencies]
percent-encoding = "2.1.0"
