[package]
name = "noodles-csi"
version = "0.2.2"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Coorindate-sorted index (CSI) format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-csi"

[features]
async = ["noodles-bgzf/async", "tokio"]

[dependencies]
bit-vec = "0.6.1"
byteorder = "1.2.3"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.3.0" }

tokio = { version = "1.8.0", optional = true, features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.8.0", features = ["fs", "macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
features = ["async"]
