[package]
name = "noodles-csi"
version = "0.2.1"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Coorindate-sorted index (CSI) format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-csi"

[dependencies]
bit-vec = "0.6.1"
byteorder = "1.2.3"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.2.0" }
