[package]
name = "noodles-cram"
version = "0.22.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.62.0"
description = "CRAM format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-cram"

[features]
async = ["async-compression", "futures", "pin-project-lite", "tokio"]

[dependencies]
bitflags = "1.2.1"
byteorder = "1.2.3"
bytes = "1.0.1"
bzip2 = "0.4.1"
flate2 = "1.0.1"
md-5 = "0.10.0"
noodles-bam = { path = "../noodles-bam", version = "0.25.0" }
noodles-core = { path = "../noodles-core", version = "0.9.0" }
noodles-fasta = { path = "../noodles-fasta", version = "0.17.0" }
noodles-sam = { path = "../noodles-sam", version = "0.22.0" }
xz2 = "0.1.6"

async-compression = { version = "0.3.8", optional = true, features = ["gzip", "tokio"] }
futures = { version = "0.3.15", optional = true, default-features = false, features = ["std"] }
pin-project-lite = { version = "0.2.6", optional = true }
tokio = { version = "1.10.0", optional = true, features = ["fs", "io-util"] }

[dev-dependencies]
noodles-sam = { path = "../noodles-sam", version = "0.22.0", features = ["async"] }
tokio = { version = "1.10.0", features = ["io-std", "macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
features = ["async"]

[[example]]
name = "cram_count_async"
required-features = ["async"]

[[example]]
name = "cram_query_async"
required-features = ["async"]

[[example]]
name = "cram_read_header_async"
required-features = ["async"]

[[example]]
name = "cram_view_async"
required-features = ["async"]

[[example]]
name = "cram_write_async"
required-features = ["async"]
