[package]
name = "noodles-cram"
version = "0.7.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "CRAM format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-cram"

[features]
async = ["async-compression", "tokio"]

[dependencies]
bitflags = "1.2.1"
byteorder = "1.2.3"
bzip2 = "0.4.1"
flate2 = "1.0.1"
md-5 = "0.9.1"
noodles-bam = { path = "../noodles-bam", version = "0.7.0" }
noodles-fasta = { path = "../noodles-fasta", version = "0.3.0" }
noodles-sam = { path = "../noodles-sam", version = "0.6.0" }
xz2 = "0.1.6"

async-compression = { version = "0.3.8", optional = true, features = ["gzip", "tokio"] }
tokio = { version = "1.10.0", optional = true, features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.10.0", features = ["fs", "macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
features = ["async"]
