[package]
name = "noodles-bam"
version = "0.4.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Binary Alignment/Map (BAM) format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-bam"

[features]
async = ["flate2", "futures", "noodles-bgzf/async", "tokio"]

[dependencies]
bit-vec = "0.6.1"
byteorder = "1.2.3"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.4.0" }
noodles-core = { path = "../noodles-core", version = "0.1.1" }
noodles-csi = { path = "../noodles-csi", version = "0.3.0" }
noodles-sam = { path = "../noodles-sam", version = "0.2.0" }

flate2 = { version = "1.0.1", optional = true }
futures = { version = "0.3.15", optional = true, default-features = false, features = ["std"] }
tokio = { version = "1.10.0", optional = true, features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.10.0", features = ["fs", "io-std", "macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
features = ["async"]
