[package]
name = "noodles-bam"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
bit-vec = "0.6.1"
byteorder = "1.2.3"
flate2 = "1.0.1"
noodles-bgzf = { path = "../noodles-bgzf" }
noodles-sam = { path = "../noodles-sam" }
