[package]
name = "noodles-bam"
version = "0.2.1"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Binary Alignment/Map (BAM) format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-bam"

[features]
async = ["futures", "noodles-bgzf/async", "pin-project-lite", "tokio"]

[dependencies]
bit-vec = "0.6.1"
byteorder = "1.2.3"
futures = { version = "0.3.15", optional = true }
noodles-bgzf = { path = "../noodles-bgzf", version = "0.2.0" }
noodles-core = { path = "../noodles-core", version = "0.1.1" }
noodles-csi = { path = "../noodles-csi", version = "0.2.1" }
noodles-sam = { path = "../noodles-sam", version = "0.2.0" }
pin-project-lite = { version = "0.2.6", optional = true }
tokio = { version = "1.8.0", optional = true, features = ["macros", "io-util"] }

[dev-dependencies]
tokio = { version = "1.8.0", features = ["fs", "io-std", "macros", "rt-multi-thread"] }
