[package]
name = "noodles-bam"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Binary Alignment/Map (BAM) format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-bam"

[dependencies]
bit-vec = "0.6.1"
byteorder = "1.2.3"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.1.0" }
noodles-core = { path = "../noodles-core", version = "0.1.0" }
noodles-csi = { path = "../noodles-csi", version = "0.1.0" }
noodles-sam = { path = "../noodles-sam", version = "0.1.0" }
