[package]
name = "noodles-bcf"
version = "0.10.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2021"
description = "Binary Call Format (BCF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-bcf"

[features]
async = ["futures", "noodles-bgzf/async", "tokio"]

[dependencies]
byteorder = "1.2.3"
indexmap = "1.4.0"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.7.0" }
noodles-core = { path = "../noodles-core", version = "0.3.0" }
noodles-csi = { path = "../noodles-csi", version = "0.4.2" }
noodles-vcf = { path = "../noodles-vcf", version = "0.11.0" }

futures = { version = "0.3.15", optional = true, default-features = false, features = ["std"] }
tokio = { version = "1.10.0", optional = true, features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.10.0", features = ["fs", "macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
features = ["async"]
