[package]
name = "noodles-bcf"
version = "0.2.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Binary Call Format (BCF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-bcf"

[dependencies]
byteorder = "1.2.3"
indexmap = "1.4.0"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.2.0" }
noodles-core = { path = "../noodles-core", version = "0.1.1" }
noodles-csi = { path = "../noodles-csi", version = "0.2.0" }
noodles-vcf = { path = "../noodles-vcf", version = "0.1.1" }
