[package]
name = "noodles-bcf"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
byteorder = "1.2.3"
noodles-bgzf = { path = "../noodles-bgzf" }
