[package]
name = "noodles-util"
version = "0.3.1"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license.workspace = true
edition.workspace = true
rust-version = "1.64.0"
description = "noodles support utilities"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-util"

[features]
alignment = [
  "noodles-bam",
  "noodles-bgzf",
  "noodles-cram",
  "noodles-fasta",
  "noodles-sam",
]

[dependencies]
noodles-bam = { path = "../noodles-bam", version = "0.25.1", optional = true }
noodles-bgzf = { path = "../noodles-bgzf", version = "0.18.0", optional = true }
noodles-cram = { path = "../noodles-cram", version = "0.22.1", optional = true }
noodles-fasta = { path = "../noodles-fasta", version = "0.17.0", optional = true }
noodles-sam = { path = "../noodles-sam", version = "0.22.1", optional = true }

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "util_alignment_rewrite"
required-features = ["alignment"]

[[example]]
name = "util_alignment_view"
required-features = ["alignment"]
