[package]
name = "noodles-util"
version = "0.1.0"
edition = "2021"

[dependencies]
noodles-bam = { path = "../noodles-bam", version = "0.19.0" }
noodles-bgzf = { path = "../noodles-bgzf", version = "0.12.0" }
noodles-core = { path = "../noodles-core", version = "0.7.0" }
noodles-cram = { path = "../noodles-cram", version = "0.16.0" }
noodles-csi = { path = "../noodles-csi", version = "0.7.0" }
noodles-fasta = { path = "../noodles-fasta", version = "0.11.0" }
noodles-sam = { path = "../noodles-sam", version = "0.16.0" }
