[package]
name = "noodles-tabix"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Tabix (TBI) format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://doc.rs/noodles-tabix"

[dependencies]
bit-vec = "0.6.1"
byteorder = "1.2.3"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.1.0" }
