[package]
name = "noodles-tabix"
version = "0.4.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Tabix (TBI) format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-tabix"

[features]
async = ["noodles-bgzf/async", "tokio"]

[dependencies]
bit-vec = "0.6.1"
byteorder = "1.2.3"
indexmap = "1.4.0"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.2.0" }
noodles-csi = { path = "../noodles-csi", version = "0.2.1" }

tokio = { version = "1.8.0", optional = true, features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.8.0", features = ["fs", "macros", "rt-multi-thread"] }
