[package]
name = "noodles-fasta"
version = "0.2.2"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "FASTA format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-fasta"

[dependencies]
memchr = "2.3.3"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.4.0" }
noodles-core = { path = "../noodles-core", version = "0.1.2" }
