[package]
name = "noodles-fastq"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
flate2 = "1.0.1"
noodles-bam = { path = "../noodles-bam" }
