[package]
name = "noodles-core"
version = "0.2.3"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2021"
description = "Shared utilities when working with noodles"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-core"

[dependencies]
noodles-sam = { path = "../noodles-sam", version = "0.6.0" }
