[package]
name = "noodles-vcf"
version = "0.3.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Variant Call Format (VCF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-vcf"

[features]
async = ["futures", "noodles-bgzf/async", "tokio"]

[dependencies]
futures = { version = "0.3.15", optional = true }
indexmap = "1.4.0"
nom = "6.1.2"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.2.0" }
noodles-core = { path = "../noodles-core", version = "0.1.2" }
noodles-csi = { path = "../noodles-csi", version = "0.2.1" }
noodles-tabix = { path = "../noodles-tabix", version = "0.4.0" }
percent-encoding = "2.1.0"
tokio = { version = "1.8.0", optional = true, features = ["io-util", "macros"] }

[dev-dependencies]
tokio = { version = "1.8.0", features = ["fs", "macros", "rt-multi-thread"] }
