[package]
name = "noodles-vcf"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
nom = "5.1.1"
noodles-bgzf = { path = "../noodles-bgzf" }
