[package]
name = "noodles-vcf"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Variant Call Format (VCF) reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://doc.rs/noodles-vcf"

[dependencies]
indexmap = "1.4.0"
nom = "6.1.2"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.1.0" }
noodles-core = { path = "../noodles-core", version = "0.1.0" }
noodles-tabix = { path = "../noodles-tabix", version = "0.1.0" }
percent-encoding = "2.1.0"
