[package]
name = "noodles-sam"
version = "0.1.1"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Sequence Alignment/Map (SAM) format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-sam"

[dependencies]
bitflags = "1.2.1"
indexmap = "1.4.0"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.2.0" }
