[package]
name = "noodles-sam"
version = "0.1.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"

[dependencies]
bitflags = "1.2.1"
indexmap = "1.4.0"
noodles-bgzf = { path = "../noodles-bgzf" }
