[package]
name = "noodles-sam"
version = "0.2.2"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2018"
description = "Sequence Alignment/Map (SAM) format reader and writer"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-sam"

[features]
async = ["noodles-bgzf/async", "tokio"]

[dependencies]
bitflags = "1.2.1"
indexmap = "1.4.0"
noodles-bgzf = { path = "../noodles-bgzf", version = "0.4.0" }

tokio = { version = "1.10.0", optional = true, features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.10.0", features = ["macros", "rt-multi-thread"] }

[package.metadata.docs.rs]
features = ["async"]
