[package]
name = "noodles-bed"
version = "0.2.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2021"
rust-version = "1.56.0"
description = "BED (Browser Extensible Data) reader"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles-bed"

[dependencies]
noodles-core = { path = "../noodles-core", version = "0.6.0" }
