[package]
name = "noodles"
version = "0.11.0"
authors = ["Michael Macias <zaeleus@gmail.com>"]
license = "MIT"
edition = "2021"
description = "Bioinformatics I/O libraries"
homepage = "https://github.com/zaeleus/noodles"
repository = "https://github.com/zaeleus/noodles"
documentation = "https://docs.rs/noodles"
readme = "../README.md"

[dependencies]
noodles-bam = { path = "../noodles-bam", version = "0.7.0", optional = true }
noodles-bcf = { path = "../noodles-bcf", version = "0.6.1", optional = true }
noodles-bgzf = { path = "../noodles-bgzf", version = "0.4.0", optional = true }
noodles-core = { path = "../noodles-core", version = "0.2.3", optional = true }
noodles-cram = { path = "../noodles-cram", version = "0.7.0", optional = true }
noodles-csi = { path = "../noodles-csi", version = "0.3.0", optional = true }
noodles-fasta = { path = "../noodles-fasta", version = "0.3.1", optional = true }
noodles-fastq = { path = "../noodles-fastq", version = "0.2.0", optional = true }
noodles-gff = { path = "../noodles-gff", version = "0.3.0", optional = true }
noodles-gtf = { path = "../noodles-gtf", version = "0.1.0", optional = true }
noodles-sam = { path = "../noodles-sam", version = "0.6.0", optional = true }
noodles-tabix = { path = "../noodles-tabix", version = "0.6.1", optional = true }
noodles-vcf = { path = "../noodles-vcf", version = "0.8.0", optional = true }

[features]
default = []

bam = ["noodles-bam"]
bcf = ["noodles-bcf"]
bgzf = ["noodles-bgzf"]
core = ["noodles-core"]
cram = ["noodles-cram"]
csi = ["noodles-csi"]
fasta = ["noodles-fasta"]
fastq = ["noodles-fastq"]
gff = ["noodles-gff"]
gtf = ["noodles-gtf"]
sam = ["noodles-sam"]
tabix = ["noodles-tabix"]
vcf = ["noodles-vcf"]

[package.metadata.docs.rs]
all-features = true
